/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import dto.Piloto;
import UI.PantallaBienvenida;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logic.LogicaDeInscripcion;

/**
 *
 * @author Usuario
 */
public class InscripcionPiloto1 extends javax.swing.JDialog {
    /*CAMPOS*/
    PantallaBienvenida PB;
    private  LogicaDeInscripcion LI = new LogicaDeInscripcion();
    /*FIN CAMPOS*/
    /**
     * Creates new form InscripcionPiloto
     */
    public InscripcionPiloto1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        PB = (PantallaBienvenida)parent;
        initComponents();
        cargarImagen();
    }

    private void cargarImagen(){
        jbAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.jpg"))); // NOI18N
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btSiguiente = new javax.swing.JButton();
        btAtras = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        lbDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jlFecha = new javax.swing.JLabel();
        jSFechaNac = new javax.swing.JSpinner();
        jbAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNombre.setText("Nombre:");
        getContentPane().add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jlApellido.setText("Apellidos:");
        getContentPane().add(jlApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        btSiguiente.setText("Siguiente");
        btSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        btAtras.setText("Atras");
        btAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 80, -1));

        lbTitulo.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbTitulo.setText("Inscripcion del Piloto");
        getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lbDni.setText("DNI:");
        getContentPane().add(lbDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 170, -1));

        jlFecha.setText("Fecha Nacimiento:");
        getContentPane().add(jlFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jSFechaNac.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1570291100487L), null, null, java.util.Calendar.DAY_OF_MONTH));
        getContentPane().add(jSFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, -1));

        jbAyuda.setIcon(new javax.swing.ImageIcon("D:\\Curso\\CFGS2º\\CFGSSegundoConGit\\DI\\NetBeansProjects\\InscripcionDeNuevosPilotos\\images\\help.jpg")); // NOI18N
        jbAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(jbAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiguienteActionPerformed
        // TODO add your handling code here:
        /*Para pasar la fecha en el formato que queramos porque sino luego no se comprueba bien*/
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date date = (Date)jSFechaNac.getValue();
        
        Piloto pilotoPersonal = new Piloto(txtDni.getText().toString(), txtNombre.getText().toString(), txtApellido.getText().toString(),formato.format(date));
        try {//Tenemos que poner el bloque de try carch porque adentro de la funcion hacemos un trows para el parse de la fecha.
            if(LI.validarCamposPilotoPersonal(this, pilotoPersonal)){
                if(LI.validarRegistroRepetidos(pilotoPersonal)){//Para validar si el registro esta ya insertado en la tabla.
                    construirPiloto(pilotoPersonal);
                }else{
                JOptionPane.showMessageDialog(this, "Ya hay un piloto registrado con este mismo DNI", "ERROR DE REGISTRO", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                mostrarPantallaError();
            }
        } catch (ParseException ex) {            
            Logger.getLogger(InscripcionPiloto1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btSiguienteActionPerformed

    private void btAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtrasActionPerformed
        // TODO add your handling code here:
        PB.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btAtrasActionPerformed

    private void jbAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAyudaActionPerformed
        // TODO add your handling code here:
        PantallaAyuda PA = new PantallaAyuda(PB, true);
        PA.setVisible(true);
    }//GEN-LAST:event_jbAyudaActionPerformed
    
    /*METODOS:*/
    private void construirPiloto(Piloto pilot){
        InscripcionPiloto2 IP2 = new InscripcionPiloto2(PB, true);
        IP2.construirPilotoDatPersonales(pilot);
        IP2.setVisible(true);
        setVisible(false);
    }
    
    private void mostrarPantallaError(){
        int resultado = JOptionPane.showConfirmDialog(this, "¿Mostrar como rellenar cada campo?", "AYUDA",JOptionPane.YES_NO_CANCEL_OPTION);
        if(resultado == JOptionPane.YES_OPTION){
            PantallaAyuda PA = new PantallaAyuda(PB,true);
            PA.setVisible(true);
        }else if(resultado == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, "Cerrando dialogo", "AYUDA", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtras;
    private javax.swing.JButton btSiguiente;
    private javax.swing.JSpinner jSFechaNac;
    private javax.swing.JButton jbAyuda;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel lbDni;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
