/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import dto.Piloto;
import UI.PantallaBienvenida;
import javax.swing.JOptionPane;
import logic.LogicaDeInscripcion;

/**
 *
 * @author Terminal
 */
public class InscripcionPiloto2 extends javax.swing.JDialog {

    /*campos de componentes*/
    PantallaBienvenida PB = new PantallaBienvenida();
    private Piloto pilotoPreparado;
    private  LogicaDeInscripcion LI = new LogicaDeInscripcion();
    /**
     * Creates new form InscripcionPiloto2
     */
    public InscripcionPiloto2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        PB = (PantallaBienvenida)parent;
        cargarImagen();
    }

    private void cargarImagen(){
        jbAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.jpg"))); // NOI18N
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlCargo = new javax.swing.JLabel();
        jlExperiencia = new javax.swing.JLabel();
        jcCargos = new javax.swing.JComboBox();
        jsAñosExp = new javax.swing.JSpinner();
        lbTitulo = new javax.swing.JLabel();
        jbSiguiente = new javax.swing.JButton();
        jbAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlCargo.setText("Cargo:");

        jlExperiencia.setText("Experiencia");

        jcCargos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Exploracion", "Patrulla", "Combate", "Especializaciones" }));
        jcCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCargosActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbTitulo.setText("Inscripcion del Piloto Parte 2");

        jbSiguiente.setText("Finalizar");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });

        jbAyuda.setIcon(new javax.swing.ImageIcon("D:\\Curso\\CFGS2º\\CFGSSegundoConGit\\DI\\NetBeansProjects\\InscripcionDeNuevosPilotos\\images\\help.jpg")); // NOI18N
        jbAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlExperiencia)
                    .addComponent(jlCargo))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsAñosExp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCargo)
                            .addComponent(jcCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlExperiencia)
                            .addComponent(jsAñosExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbSiguiente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCargosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcCargosActionPerformed

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
        // TODO add your handling code here:
        construirPilotoDatProfesionales();
        if(LI.validarCamposPilotoProfesional(this, pilotoPreparado)){
            LI.addPiloto(pilotoPreparado);
            setVisible(false);
            
        }else{
            mostrarPantallaError();
        }
    }//GEN-LAST:event_jbSiguienteActionPerformed

    private void jbAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAyudaActionPerformed
        // TODO add your handling code here:
        PantallaAyuda PA = new PantallaAyuda(PB, true);
        PA.setVisible(true);
    }//GEN-LAST:event_jbAyudaActionPerformed
    
    
    /*METODOS*/
    
    private void mostrarPantallaError(){
        int resultado = JOptionPane.showConfirmDialog(this, "¿Mostrar como rellenar cada campo?", "AYUDA",JOptionPane.YES_NO_CANCEL_OPTION);
        if(resultado == JOptionPane.YES_OPTION){
            PantallaAyuda PA = new PantallaAyuda(PB,true);
            PA.setVisible(true);
        }else if(resultado == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, "Cerrando dialogo", "AYUDA", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void construirPilotoDatPersonales(Piloto piloto){
        pilotoPreparado = new Piloto(piloto.getDni(), piloto.getNombre(), piloto.getApellido(), "" ,0 , piloto.getFechaNac());
    }
    
    private void construirPilotoDatProfesionales(){
        pilotoPreparado.setCargo(jcCargos.getSelectedItem().toString());
        pilotoPreparado.setExperiencia(Integer.parseInt(jsAñosExp.getValue().toString()));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAyuda;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JComboBox jcCargos;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlExperiencia;
    private javax.swing.JSpinner jsAñosExp;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
