/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Terminal
 */
public class PantallaModificacionPiloto extends javax.swing.JDialog {

    /*CAMPOS*/
    DatosPiloto DP;
    /**
     * Creates new form PantallaModificacion
     */
    public PantallaModificacionPiloto(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        DP = (DatosPiloto)parent;
        initComponents();
        cargarImagen();
    }

    private void cargarImagen(){
        jbAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.jpg"))); // NOI18N
        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelMod1.jpg"))); // NOI18N
        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelMod2.jpg"))); // NOI18N
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPPersonal = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        lbDNI = new javax.swing.JLabel();
        jlFechaNac = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jSFechaNac = new javax.swing.JSpinner();
        jbAyuda = new javax.swing.JButton();
        imagen1 = new javax.swing.JLabel();
        jPProfesional = new javax.swing.JPanel();
        jlCargo = new javax.swing.JLabel();
        jlExperiencia = new javax.swing.JLabel();
        btModificar = new javax.swing.JButton();
        jcCargo = new javax.swing.JComboBox();
        jsExperiencia = new javax.swing.JSpinner();
        imagen2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPPersonal.setBackground(new java.awt.Color(153, 255, 153));
        jPPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(0, 0, 0));
        jlNombre.setText("NOMBRE:");
        jPPersonal.add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jlApellido.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlApellido.setForeground(new java.awt.Color(0, 0, 0));
        jlApellido.setText("APELLIDO:");
        jPPersonal.add(jlApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        lbDNI.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbDNI.setForeground(new java.awt.Color(0, 0, 0));
        lbDNI.setText("DNI:");
        jPPersonal.add(lbDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jlFechaNac.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlFechaNac.setForeground(new java.awt.Color(0, 0, 0));
        jlFechaNac.setText("FECHA NACIMIENTO:");
        jPPersonal.add(jlFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPPersonal.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, -1));
        jPPersonal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 190, -1));
        jPPersonal.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, -1));

        jSFechaNac.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        jPPersonal.add(jSFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, -1));

        jbAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAyudaActionPerformed(evt);
            }
        });
        jPPersonal.add(jbAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));
        jPPersonal.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 370, 220));

        jPanel1.add(jPPersonal);

        jPProfesional.setBackground(new java.awt.Color(255, 204, 204));
        jPProfesional.setFocusable(false);
        jPProfesional.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCargo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlCargo.setForeground(new java.awt.Color(0, 0, 0));
        jlCargo.setText("CARGO:");
        jPProfesional.add(jlCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jlExperiencia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlExperiencia.setForeground(new java.awt.Color(0, 0, 0));
        jlExperiencia.setText("EXPERIENCIA:");
        jPProfesional.add(jlExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btModificar.setText("MODIFICAR");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });
        jPProfesional.add(btModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jcCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Exploracion", "Patrulla", "Combate", "Especializaciones" }));
        jcCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCargoActionPerformed(evt);
            }
        });
        jPProfesional.add(jcCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 200, -1));
        jPProfesional.add(jsExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 200, -1));
        jPProfesional.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 220));

        jPanel1.add(jPProfesional);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*METODOS*/
    
    
    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        try {
            // TODO add your handling code here:
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date date = (Date)jSFechaNac.getValue();
            
            String[] recogerDatos = new String[6];
            recogerDatos [0] = txtDNI.getText();//DNI
            recogerDatos [1] = txtNombre.getText();//NOMBRE
            recogerDatos [2] = txtApellido.getText();//APELLIDO
            recogerDatos [3] = formato.format(date);//FECHA NAC
            recogerDatos [4] = jcCargo.getSelectedItem().toString();//CARGO
            recogerDatos [5] = String.valueOf(jsExperiencia.getComponentCount());//EXP
            
            DP.modificarDatos(recogerDatos);//Le pasamos los datos modificacos
            setVisible(false);
            DP.setVisible(true);//Para refrescar el model de la pantalla.
            
            
        } catch (ParseException ex) {
            Logger.getLogger(PantallaModificacionPiloto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btModificarActionPerformed

    private void jcCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCargoActionPerformed

    private void jbAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAyudaActionPerformed
        // TODO add your handling code here:
        PantallaAyuda PA = new PantallaAyuda(null, true);
        PA.setVisible(true);
    }//GEN-LAST:event_jbAyudaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btModificar;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JPanel jPPersonal;
    private javax.swing.JPanel jPProfesional;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSFechaNac;
    private javax.swing.JButton jbAyuda;
    private javax.swing.JComboBox jcCargo;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlExperiencia;
    private javax.swing.JLabel jlFechaNac;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JSpinner jsExperiencia;
    private javax.swing.JLabel lbDNI;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
