/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Terminal
 */
public class PantallaBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form PantallaBienvenida
     */
    public PantallaBienvenida() {
        initComponents();
        cargarImagen();
    }
    private void cargarImagen(){
        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cielo.jpg"))); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        BTNext = new javax.swing.JButton();
        btMostrarTabla = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        lbpresentation = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNext.setBackground(new java.awt.Color(204, 204, 204));
        BTNext.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BTNext.setForeground(new java.awt.Color(51, 51, 51));
        BTNext.setText("DAR DE ALTA");
        BTNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNextActionPerformed(evt);
            }
        });
        jPanelFondo.add(BTNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 130, 37));

        btMostrarTabla.setBackground(new java.awt.Color(204, 204, 204));
        btMostrarTabla.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btMostrarTabla.setForeground(new java.awt.Color(51, 51, 51));
        btMostrarTabla.setText("REGISTROS");
        btMostrarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarTablaActionPerformed(evt);
            }
        });
        jPanelFondo.add(btMostrarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 40));

        btSalir.setBackground(new java.awt.Color(204, 204, 204));
        btSalir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btSalir.setForeground(new java.awt.Color(51, 51, 51));
        btSalir.setText("EXIT");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanelFondo.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, 40));

        lbpresentation.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbpresentation.setForeground(new java.awt.Color(204, 255, 204));
        lbpresentation.setText("INSCRIPCION FUERZAS AEREAS");
        jPanelFondo.add(lbpresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));
        jPanelFondo.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 601, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNextActionPerformed
        // TODO add your handling code here:
        InscripcionPiloto1 IP1 = new InscripcionPiloto1(this, true);
        IP1.setVisible(true);
    }//GEN-LAST:event_BTNextActionPerformed

    private void btMostrarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarTablaActionPerformed
        // TODO add your handling code here:
        DatosPiloto DP = new DatosPiloto(this, true);
        DP.setVisible(true);

    }//GEN-LAST:event_btMostrarTablaActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNext;
    private javax.swing.JButton btMostrarTabla;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JLabel lbpresentation;
    // End of variables declaration//GEN-END:variables
}
